# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\src\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(684, 469)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_2.setSpacing(9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.search_bar = QtWidgets.QLineEdit(self.centralwidget)
        self.search_bar.setObjectName("search_bar")
        self.verticalLayout_2.addWidget(self.search_bar)
        self.movie_tree = QtWidgets.QTreeWidget(self.centralwidget)
        self.movie_tree.setRootIsDecorated(False)
        self.movie_tree.setObjectName("movie_tree")
        self.verticalLayout_2.addWidget(self.movie_tree)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.poster = QtWidgets.QLabel(self.centralwidget)
        self.poster.setMinimumSize(QtCore.QSize(130, 190))
        self.poster.setMaximumSize(QtCore.QSize(130, 190))
        self.poster.setStyleSheet("#poster { padding: 3px; background: #d2d2d2}")
        self.poster.setText("")
        self.poster.setScaledContents(True)
        self.poster.setObjectName("poster")
        self.horizontalLayout_2.addWidget(self.poster)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.movie_title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.movie_title.setFont(font)
        self.movie_title.setObjectName("movie_title")
        self.verticalLayout.addWidget(self.movie_title)
        self.description = QtWidgets.QLabel(self.centralwidget)
        self.description.setMinimumSize(QtCore.QSize(0, 0))
        self.description.setStyleSheet("#description {\n"
"    border: 1px solid #d2d2d2;\n"
"}")
        self.description.setScaledContents(False)
        self.description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.description.setWordWrap(True)
        self.description.setObjectName("description")
        self.verticalLayout.addWidget(self.description)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.quality_combo = QtWidgets.QComboBox(self.centralwidget)
        self.quality_combo.setEnabled(True)
        self.quality_combo.setObjectName("quality_combo")
        self.horizontalLayout.addWidget(self.quality_combo)
        self.subtitle_combo = QtWidgets.QComboBox(self.centralwidget)
        self.subtitle_combo.setObjectName("subtitle_combo")
        self.horizontalLayout.addWidget(self.subtitle_combo)
        self.play_button = QtWidgets.QPushButton(self.centralwidget)
        self.play_button.setObjectName("play_button")
        self.horizontalLayout.addWidget(self.play_button)
        self.horizontalLayout.setStretch(0, 40)
        self.horizontalLayout.setStretch(1, 40)
        self.horizontalLayout.setStretch(2, 10)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 10)
        self.verticalLayout.setStretch(1, 60)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.status_bar = QtWidgets.QLabel(self.centralwidget)
        self.status_bar.setObjectName("status_bar")
        self.verticalLayout_2.addWidget(self.status_bar)
        self.verticalLayout_2.setStretch(0, 5)
        self.verticalLayout_2.setStretch(1, 60)
        self.verticalLayout_2.setStretch(2, 20)
        self.verticalLayout_2.setStretch(3, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 684, 21))
        self.menubar.setObjectName("menubar")
        self.menuPrefences = QtWidgets.QMenu(self.menubar)
        self.menuPrefences.setObjectName("menuPrefences")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuPlugins = QtWidgets.QMenu(self.menubar)
        self.menuPlugins.setEnabled(False)
        self.menuPlugins.setObjectName("menuPlugins")
        MainWindow.setMenuBar(self.menubar)
        self.actionVideo_player = QtWidgets.QAction(MainWindow)
        self.actionVideo_player.setObjectName("actionVideo_player")
        self.menuPrefences.addAction(self.actionVideo_player)
        self.menubar.addAction(self.menuPrefences.menuAction())
        self.menubar.addAction(self.menuPlugins.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.search_bar.setPlaceholderText(_translate("MainWindow", "Search"))
        self.movie_tree.headerItem().setText(0, _translate("MainWindow", "Title"))
        self.movie_tree.headerItem().setText(1, _translate("MainWindow", "Length"))
        self.movie_tree.headerItem().setText(2, _translate("MainWindow", "Plugin"))
        self.movie_title.setText(_translate("MainWindow", "No Title"))
        self.description.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-style:italic;\">No movie description is availabe at this time. Sorry.</span></p></body></html>"))
        self.play_button.setText(_translate("MainWindow", "PLAY!"))
        self.status_bar.setText(_translate("MainWindow", "READY"))
        self.menuPrefences.setTitle(_translate("MainWindow", "Edit"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.menuPlugins.setTitle(_translate("MainWindow", "Plugins"))
        self.actionVideo_player.setText(_translate("MainWindow", "Preferences"))

